# Generated by Django 3.2.4 on 2021-06-19 11:44

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import common.fields.autoslugfield


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified_at",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255, verbose_name="Title")),
                (
                    "slug",
                    common.fields.autoslugfield.AutoSlugField(
                        blank=True,
                        editable=False,
                        max_length=128,
                        populate_from=["title", "related_id"],
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("related_id", models.BigIntegerField()),
                ("country_code", models.CharField(db_index=True, max_length=3)),
                ("lat", models.FloatField()),
                ("lon", models.JSONField()),
            ],
            options={
                "ordering": ("title", "country_code"),
            },
        ),
    ]
